targets:
  $default:
    builders:
      json_serializable:json_serializable:
        generate_for:
          - lib/data/dtos/**
          - lib/domain/entities/**
      retrofit_generator:
        generate_for:
          - lib/data/sources/remote/tasks_api.dart
