targets:
  $default:
    builders:
      json_serializable:json_serializable:
        generate_for:
          - lib/data/dto/**
          - lib/domain/models/**
      retrofit_generator:
        generate_for:
          - lib/data/sources/api_client.dart
