name: app
description: "Tasky — Todo List App"
publish_to: "none"
version: 1.3.0

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ^3.22.2

dependencies:
  bloc_concurrency: ^0.2.5
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.2
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  retrofit_generator: ^8.1.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  android: ic_launcher
  image_path: assets/app_icon.png
  adaptive_icon_background: "#f7f7f7"
  adaptive_icon_foreground: assets/app_icon_foreground.png
